using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Xam.Plugin.Abstractions;
using Xamarin.Forms;

namespace EbookReader {
    public class App : Application {

        public App() {

            var webView = new FormsWebView() {
                ContentType = Xam.Plugin.Abstractions.Enumerations.WebViewContentType.StringData,
                Source = GetHtml(),
                WidthRequest = 500,
                HeightRequest = 500
            };

            webView.OnContentLoaded += WebView_OnContentLoaded;

            webView.RegisterGlobalCallback("csDebug", (str) => {
                webView.InjectJavascript(string.Format("scroll({0})", str));
            });

            var content = new ContentPage {
                Title = "EbookReader",
                Content = new StackLayout {
                    VerticalOptions = LayoutOptions.Center,
                    Children = {
                        webView
                    }
                }
            };

            MainPage = new NavigationPage(content);
        }
        
        private void WebView_OnContentLoaded(Xam.Plugin.Abstractions.Events.Inbound.ContentLoadedDelegate eventObj) {
            eventObj.Sender.InjectJavascript("init()");
        }


        protected string GetHtml() {
            return @"
<html>
    <head>
        <script type='text/javascript' src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
        <script type='text/javascript'>
            function init(){
                $(document).on('click', function(e){
                    var to = e.pageX > 250 ? '100' : '-100';
                    csDebug(to);
                });
            }
            function scroll(top){
                $('html, body').animate({
                    scrollTop: $(window).scrollTop() + parseInt(top)
                }, 0);
            }
        </script>
        <style>
            body {
                overflow: hidden;
            }
        </style>
    </head>
    <body>
        <h1>nadpis</h1>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Pellentesque ipsum. Maecenas sollicitudin. Nullam sit amet magna in magna gravida vehicula. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Donec quis nibh at felis congue commodo. Etiam quis quam. Nulla est. Aenean vel massa quis mauris vehicula lacinia. Aenean placerat. Donec iaculis gravida nulla.</p>

<p>Aenean id metus id velit ullamcorper pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Aliquam erat volutpat. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sagittis hendrerit ante. Aenean fermentum risus id tortor. Nunc auctor. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Integer in sapien. Nullam rhoncus aliquam metus. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Maecenas aliquet accumsan leo.</p>

<p>Nulla quis diam. Aliquam erat volutpat. Integer vulputate sem a nibh rutrum consequat. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Praesent in mauris eu tortor porttitor accumsan. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Curabitur vitae diam non enim vestibulum interdum. Suspendisse nisl. Etiam quis quam. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nullam dapibus fermentum ipsum. Maecenas lorem. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Mauris elementum mauris vitae tortor. Aliquam in lorem sit amet leo accumsan lacinia.</p>

<p>Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nunc dapibus tortor vel mi dapibus sollicitudin. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Integer imperdiet lectus quis justo. Vivamus porttitor turpis ac leo. Aliquam id dolor. Integer imperdiet lectus quis justo. Integer vulputate sem a nibh rutrum consequat. Vivamus luctus egestas leo. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Nullam rhoncus aliquam metus. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Praesent id justo in neque elementum ultrices. Praesent vitae arcu tempor neque lacinia pretium.</p>

<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Cras elementum. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Nulla est. Donec quis nibh at felis congue commodo. Maecenas aliquet accumsan leo. Vestibulum fermentum tortor id mi. Nullam eget nisl. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Vivamus porttitor turpis ac leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean id metus id velit ullamcorper pulvinar. Duis viverra diam non justo. Etiam commodo dui eget wisi. Mauris elementum mauris vitae tortor. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Fusce consectetuer risus a nunc.</p>

<p>Etiam neque. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Aliquam erat volutpat. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nulla quis diam. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Proin mattis lacinia justo. Etiam neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Suspendisse nisl. Maecenas libero. Etiam dictum tincidunt diam. Nullam at arcu a est sollicitudin euismod. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Etiam neque. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Etiam quis quam. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>In dapibus augue non sapien. Pellentesque arcu. Sed convallis magna eu sem. In rutrum. Nullam rhoncus aliquam metus. Maecenas lorem. Nam sed tellus id magna elementum tincidunt. Duis condimentum augue id magna semper rutrum. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam egestas wisi a erat. Etiam dictum tincidunt diam. Nam quis nulla. Morbi scelerisque luctus velit. Curabitur vitae diam non enim vestibulum interdum. Fusce wisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim.</p>

<p>Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Integer vulputate sem a nibh rutrum consequat. Morbi scelerisque luctus velit. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. In rutrum. Praesent vitae arcu tempor neque lacinia pretium. Aenean vel massa quis mauris vehicula lacinia. Nullam at arcu a est sollicitudin euismod.</p>

<p>Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Vivamus ac leo pretium faucibus. Donec vitae arcu. Aenean fermentum risus id tortor. Mauris elementum mauris vitae tortor. Praesent dapibus. Aenean fermentum risus id tortor. Aenean vel massa quis mauris vehicula lacinia. Morbi scelerisque luctus velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. In rutrum.</p>

<p>Suspendisse sagittis ultrices augue. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Suspendisse nisl. Integer lacinia. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Etiam egestas wisi a erat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Phasellus rhoncus. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Curabitur vitae diam non enim vestibulum interdum. Aenean vel massa quis mauris vehicula lacinia. Nunc dapibus tortor vel mi dapibus sollicitudin. Maecenas sollicitudin. Mauris elementum mauris vitae tortor. Nullam at arcu a est sollicitudin euismod. Donec iaculis gravida nulla. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus.</p>

<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam sit amet magna in magna gravida vehicula. Etiam commodo dui eget wisi. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nulla quis diam. Maecenas lorem. Phasellus et lorem id felis nonummy placerat. Sed ac dolor sit amet purus malesuada congue. Etiam dictum tincidunt diam. Aliquam in lorem sit amet leo accumsan lacinia. Phasellus rhoncus. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Nullam dapibus fermentum ipsum. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nunc tincidunt ante vitae massa.</p>

<p>Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Vestibulum fermentum tortor id mi. Donec vitae arcu. Maecenas aliquet accumsan leo. Integer vulputate sem a nibh rutrum consequat. Duis risus. Nullam at arcu a est sollicitudin euismod. Aliquam erat volutpat. Duis condimentum augue id magna semper rutrum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Nullam sit amet magna in magna gravida vehicula. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Et harum quidem rerum facilis est et expedita distinctio. Duis pulvinar.</p>

<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Et harum quidem rerum facilis est et expedita distinctio. In dapibus augue non sapien. Proin in tellus sit amet nibh dignissim sagittis. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. In enim a arcu imperdiet malesuada. In convallis. Duis risus. Nunc dapibus tortor vel mi dapibus sollicitudin. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

<p>Sed ac dolor sit amet purus malesuada congue. Nam quis nulla. Curabitur sagittis hendrerit ante. Integer tempor. Mauris metus. Maecenas sollicitudin. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam commodo dui eget wisi. Etiam egestas wisi a erat. Etiam commodo dui eget wisi. Proin in tellus sit amet nibh dignissim sagittis. Nulla pulvinar eleifend sem. Etiam egestas wisi a erat. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.</p>

<p>Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris tincidunt sem sed arcu. Phasellus et lorem id felis nonummy placerat. Pellentesque sapien. Proin mattis lacinia justo. Nullam at arcu a est sollicitudin euismod. Nulla est. Sed convallis magna eu sem. Aliquam ante. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Integer tempor. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Phasellus et lorem id felis nonummy placerat. Nullam dapibus fermentum ipsum. Aenean id metus id velit ullamcorper pulvinar. Nullam at arcu a est sollicitudin euismod. Etiam neque. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui.</p>

<p>Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Aliquam erat volutpat. Nulla non arcu lacinia neque faucibus fringilla. Curabitur bibendum justo non orci. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Etiam dictum tincidunt diam. Quisque tincidunt scelerisque libero. Et harum quidem rerum facilis est et expedita distinctio. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Aenean id metus id velit ullamcorper pulvinar.</p>

<p>Fusce suscipit libero eget elit. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Integer vulputate sem a nibh rutrum consequat. Fusce suscipit libero eget elit. Duis viverra diam non justo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer pellentesque quam vel velit. Fusce consectetuer risus a nunc. Aenean fermentum risus id tortor. Proin mattis lacinia justo. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Quisque tincidunt scelerisque libero. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam.</p>

<p>Quisque tincidunt scelerisque libero. Mauris metus. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Sed convallis magna eu sem. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam egestas wisi a erat. Vivamus porttitor turpis ac leo. Fusce nibh. Aliquam in lorem sit amet leo accumsan lacinia. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Aenean vel massa quis mauris vehicula lacinia. Aliquam erat volutpat. Donec vitae arcu. Fusce nibh. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem.</p>

<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nullam dapibus fermentum ipsum. Nulla pulvinar eleifend sem. Nulla quis diam. Nulla non lectus sed nisl molestie malesuada. Integer lacinia. Nunc dapibus tortor vel mi dapibus sollicitudin. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis pulvinar. Integer in sapien. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

<p>Maecenas libero. Aenean fermentum risus id tortor. Etiam egestas wisi a erat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Vivamus porttitor turpis ac leo. In convallis. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Vivamus ac leo pretium faucibus. Et harum quidem rerum facilis est et expedita distinctio. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Mauris dictum facilisis augue. Etiam quis quam. Pellentesque arcu. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur bibendum justo non orci. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat.</p>

<p>In rutrum. Vivamus luctus egestas leo. In dapibus augue non sapien. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Nunc dapibus tortor vel mi dapibus sollicitudin. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Et harum quidem rerum facilis est et expedita distinctio. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Etiam egestas wisi a erat. Maecenas libero. Nunc auctor. In convallis. In dapibus augue non sapien. Nunc auctor.</p>

<p>Cras elementum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Nulla quis diam. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Aliquam in lorem sit amet leo accumsan lacinia. Nulla non lectus sed nisl molestie malesuada. Morbi scelerisque luctus velit. Vestibulum fermentum tortor id mi. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui.</p>

<p>Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Proin in tellus sit amet nibh dignissim sagittis. Nulla pulvinar eleifend sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Mauris tincidunt sem sed arcu. Curabitur bibendum justo non orci. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Cras elementum. Integer imperdiet lectus quis justo. Nunc auctor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Donec vitae arcu. Aliquam in lorem sit amet leo accumsan lacinia. Nullam sit amet magna in magna gravida vehicula. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Fusce wisi. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante.</p>

<p>Curabitur sagittis hendrerit ante. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam at arcu a est sollicitudin euismod. Duis risus. Nullam sit amet magna in magna gravida vehicula. Nulla non arcu lacinia neque faucibus fringilla. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Nullam faucibus mi quis velit. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Quisque porta. Praesent in mauris eu tortor porttitor accumsan. Curabitur sagittis hendrerit ante. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>

<p>In convallis. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Integer lacinia. Praesent in mauris eu tortor porttitor accumsan. Etiam egestas wisi a erat. Curabitur vitae diam non enim vestibulum interdum. Curabitur sagittis hendrerit ante. Aliquam ornare wisi eu metus. Suspendisse sagittis ultrices augue. Nulla est. Praesent id justo in neque elementum ultrices. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Maecenas aliquet accumsan leo. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Nulla est. Fusce suscipit libero eget elit. Fusce nibh.</p>

<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris metus. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Nam quis nulla. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Pellentesque arcu. Etiam bibendum elit eget erat. Nullam sit amet magna in magna gravida vehicula. Aliquam erat volutpat. Mauris tincidunt sem sed arcu. Nulla non arcu lacinia neque faucibus fringilla. Nullam faucibus mi quis velit.</p>

<p>Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Aliquam ornare wisi eu metus. Nam quis nulla. Integer tempor. Praesent vitae arcu tempor neque lacinia pretium. Aenean id metus id velit ullamcorper pulvinar. Fusce tellus. Nulla est. Et harum quidem rerum facilis est et expedita distinctio. Maecenas aliquet accumsan leo. Duis pulvinar.</p>

<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin mattis lacinia justo. Aliquam erat volutpat. Aenean placerat. Nunc auctor. Etiam quis quam. Etiam bibendum elit eget erat. Nulla pulvinar eleifend sem. Praesent dapibus. In dapibus augue non sapien. Sed ac dolor sit amet purus malesuada congue. Praesent id justo in neque elementum ultrices. Aliquam id dolor. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Pellentesque ipsum.</p>

<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Et harum quidem rerum facilis est et expedita distinctio. Etiam neque. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed ac dolor sit amet purus malesuada congue. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Cras elementum. Etiam dictum tincidunt diam. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Nulla pulvinar eleifend sem. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Integer lacinia. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nullam eget nisl.</p>

<p>Etiam commodo dui eget wisi. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Nulla quis diam. Nullam sit amet magna in magna gravida vehicula. Praesent dapibus. Aenean vel massa quis mauris vehicula lacinia. Maecenas sollicitudin. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Curabitur vitae diam non enim vestibulum interdum. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Vivamus luctus egestas leo.</p>

<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Phasellus et lorem id felis nonummy placerat. Praesent dapibus. Praesent vitae arcu tempor neque lacinia pretium. Nunc tincidunt ante vitae massa. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Etiam bibendum elit eget erat. Morbi scelerisque luctus velit. Sed convallis magna eu sem. Integer pellentesque quam vel velit. Etiam bibendum elit eget erat. Sed ac dolor sit amet purus malesuada congue. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Integer pellentesque quam vel velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce suscipit libero eget elit. Curabitur bibendum justo non orci. Aliquam erat volutpat. Etiam neque. Et harum quidem rerum facilis est et expedita distinctio.</p>

<p>Fusce tellus. Etiam bibendum elit eget erat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla pulvinar eleifend sem. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Nam quis nulla. Mauris dictum facilisis augue. Aliquam ornare wisi eu metus. Vivamus porttitor turpis ac leo. Praesent dapibus. Fusce nibh. Phasellus rhoncus.</p>

<p>Integer in sapien. Donec quis nibh at felis congue commodo. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Aliquam ornare wisi eu metus. Fusce tellus. Suspendisse nisl. Praesent id justo in neque elementum ultrices. Sed convallis magna eu sem. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Mauris dictum facilisis augue. Pellentesque pretium lectus id turpis. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Vivamus luctus egestas leo. Etiam bibendum elit eget erat. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Aenean fermentum risus id tortor. Cras pede libero, dapibus nec, pretium sit amet, tempor quis.</p>

<p>Suspendisse nisl. Curabitur sagittis hendrerit ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nunc dapibus tortor vel mi dapibus sollicitudin. Nullam sit amet magna in magna gravida vehicula. Integer vulputate sem a nibh rutrum consequat. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Aliquam erat volutpat. Praesent in mauris eu tortor porttitor accumsan. Vivamus ac leo pretium faucibus. Mauris tincidunt sem sed arcu.</p>

<p>Etiam neque. Mauris dictum facilisis augue. Mauris metus. Praesent id justo in neque elementum ultrices. Aliquam ornare wisi eu metus. Vivamus porttitor turpis ac leo. Nulla quis diam. Etiam neque. In rutrum. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Integer vulputate sem a nibh rutrum consequat. Phasellus faucibus molestie nisl. Nulla pulvinar eleifend sem. Et harum quidem rerum facilis est et expedita distinctio. Nam quis nulla. Duis condimentum augue id magna semper rutrum.</p>

<p>In dapibus augue non sapien. Nullam faucibus mi quis velit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla non lectus sed nisl molestie malesuada. Nam quis nulla. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Morbi scelerisque luctus velit. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Fusce tellus. Pellentesque sapien. Integer pellentesque quam vel velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Phasellus rhoncus. Pellentesque arcu. Curabitur vitae diam non enim vestibulum interdum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.</p>

<p>Praesent vitae arcu tempor neque lacinia pretium. Etiam egestas wisi a erat. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Proin mattis lacinia justo. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Integer malesuada. Nullam rhoncus aliquam metus. Fusce nibh. Maecenas sollicitudin. Nullam faucibus mi quis velit. Phasellus faucibus molestie nisl. Nam sed tellus id magna elementum tincidunt. Donec quis nibh at felis congue commodo.</p>

<p>Nunc tincidunt ante vitae massa. Aliquam erat volutpat. Quisque porta. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Mauris dictum facilisis augue. Nullam rhoncus aliquam metus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla quis diam. Fusce wisi. Cras elementum. Duis viverra diam non justo. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Pellentesque arcu.</p>

<p>Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Duis condimentum augue id magna semper rutrum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque tincidunt scelerisque libero. Integer malesuada. Aliquam erat volutpat. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Duis condimentum augue id magna semper rutrum. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Sed ac dolor sit amet purus malesuada congue. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Aliquam erat volutpat. Aliquam erat volutpat. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus.</p>

<p>Etiam dictum tincidunt diam. Aliquam erat volutpat. Duis risus. Nulla est. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Fusce suscipit libero eget elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam dictum tincidunt diam. Pellentesque pretium lectus id turpis. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis condimentum augue id magna semper rutrum. Maecenas libero. Aenean vel massa quis mauris vehicula lacinia. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor.</p>

<p>Aliquam erat volutpat. Fusce wisi. Morbi scelerisque luctus velit. Proin in tellus sit amet nibh dignissim sagittis. Phasellus faucibus molestie nisl. Etiam quis quam. Donec quis nibh at felis congue commodo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Duis risus. Integer imperdiet lectus quis justo. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Aliquam in lorem sit amet leo accumsan lacinia. Etiam posuere lacus quis dolor. Phasellus rhoncus. Pellentesque sapien. Integer malesuada. Fusce aliquam vestibulum ipsum.</p>

<p>Etiam dictum tincidunt diam. Maecenas aliquet accumsan leo. Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Nulla est. Praesent dapibus. Etiam commodo dui eget wisi. Quisque tincidunt scelerisque libero. Nunc dapibus tortor vel mi dapibus sollicitudin. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Integer malesuada. Nulla pulvinar eleifend sem. Nullam sit amet magna in magna gravida vehicula. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Etiam quis quam. Integer vulputate sem a nibh rutrum consequat. Pellentesque arcu.</p>

<p>Praesent id justo in neque elementum ultrices. Proin in tellus sit amet nibh dignissim sagittis. Praesent dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Nulla pulvinar eleifend sem. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Etiam quis quam. Nunc auctor. In convallis. Aenean vel massa quis mauris vehicula lacinia. Vivamus ac leo pretium faucibus. Vivamus luctus egestas leo. Curabitur bibendum justo non orci. Etiam neque. Phasellus et lorem id felis nonummy placerat. Aliquam id dolor. In rutrum.</p>

<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque ipsum. Maecenas aliquet accumsan leo. Nulla non arcu lacinia neque faucibus fringilla. Nam quis nulla. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Praesent vitae arcu tempor neque lacinia pretium. Proin in tellus sit amet nibh dignissim sagittis. Pellentesque pretium lectus id turpis. Nunc dapibus tortor vel mi dapibus sollicitudin. Vivamus luctus egestas leo. Aliquam erat volutpat. Duis viverra diam non justo. Nunc auctor. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nullam rhoncus aliquam metus. Nullam eget nisl.</p>

<p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Phasellus rhoncus. In rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Pellentesque arcu. Nulla est. Etiam posuere lacus quis dolor. Duis viverra diam non justo. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Donec quis nibh at felis congue commodo. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Nulla est. Aliquam ornare wisi eu metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.</p>

<p>Ut tempus purus at lorem. Aenean vel massa quis mauris vehicula lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Duis condimentum augue id magna semper rutrum. Fusce tellus. Suspendisse nisl. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Sed ac dolor sit amet purus malesuada congue. Etiam dictum tincidunt diam. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Mauris elementum mauris vitae tortor. Suspendisse nisl. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin mattis lacinia justo. Aenean fermentum risus id tortor. Aliquam erat volutpat. Morbi scelerisque luctus velit.</p>

<p>Proin mattis lacinia justo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nullam eget nisl. Proin in tellus sit amet nibh dignissim sagittis. Etiam dictum tincidunt diam. Etiam bibendum elit eget erat. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Maecenas aliquet accumsan leo. Phasellus rhoncus. Et harum quidem rerum facilis est et expedita distinctio. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Etiam posuere lacus quis dolor. Aenean id metus id velit ullamcorper pulvinar. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Fusce suscipit libero eget elit. Aenean id metus id velit ullamcorper pulvinar. Suspendisse sagittis ultrices augue. Mauris tincidunt sem sed arcu. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero.</p>

<p>Nullam eget nisl. Pellentesque arcu. Integer lacinia. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Nullam faucibus mi quis velit. Pellentesque ipsum. Etiam posuere lacus quis dolor. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Mauris dictum facilisis augue. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat.</p>

<p>Maecenas sollicitudin. Vivamus ac leo pretium faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Duis risus. Praesent vitae arcu tempor neque lacinia pretium. Mauris tincidunt sem sed arcu. Vivamus luctus egestas leo. Nullam at arcu a est sollicitudin euismod. Integer vulputate sem a nibh rutrum consequat. Etiam quis quam. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Vivamus ac leo pretium faucibus. Etiam neque. Integer tempor. Nam quis nulla. Donec vitae arcu. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Integer in sapien.</p>

<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. In dapibus augue non sapien. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Sed ac dolor sit amet purus malesuada congue. Pellentesque arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Aenean id metus id velit ullamcorper pulvinar. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nulla quis diam.</p>
    </body>
</html>
";
        }

        protected override void OnStart() {
            // Handle when your app starts
        }

        protected override void OnSleep() {
            // Handle when your app sleeps
        }

        protected override void OnResume() {
            // Handle when your app resumes
        }
    }
}
